<?php
/**
 * Template Name: Privacy
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package signyouremail
 */
?>
<?php  echo get_header(); ?>
<section class="content-wrapper section">
    <div class="container">
        <h1 class="title is-1">Privacy Policy</h1>
        <p>signyouremail ("us", "we", or "our") operates the https://www.signyouremail.io website (the "Service").</p>
        <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use
            our Service and the choices you have associated with that data.</p>
        <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of
            information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this
            Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://www.signyouremail.io</p>
        <br>

        <h2 class="is-size-4">Definitions</h2>
        <p><strong>Service</strong>: Service is the https://www.signyouremail.io website operated by signyouremail.</p>
        <p><strong>Personal Data</strong>: Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
        <p><strong>Usage Data</strong>: Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
        <p><strong>Cookies</strong>: Cookies are small pieces of data stored on your device (computer or mobile device).</p>
        <p><strong>Data Controller</strong>: Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>
        <p><strong>Data Processors (or Service Providers)</strong>: Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
        <p><strong>Data Subject (or User)</strong>: Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>
        <br>

        <h2 class="is-size-4">What personal information do we collect from the people that visit our blog, website or app?</h2>
        
        <p>When ordering or registering on our site, as appropriate, you may be asked to enter your name, email address, mailing address, phone number or other details to help you with your experience.</p>
        <br>
        <h2 class="is-size-4">When do we collect information?</h2>
        
        <p>We collect information from you when you register on our site, fill out a form or enter information on our site.</p>
        
        <br>
        <h2 class="is-size-4">How do we use your information?</h2>
        
        <p>We may use the information we collect from you when you register, make a purchase, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:</p>
        <p>
            • To personalize your experience and to allow us to deliver the type of content and product offerings in which you are most interested.
            • To allow us to better service you in responding to your customer service requests.
            • To administer a contest, promotion, survey or other site feature.
            • To quickly process your transactions.
        </p>
        <br>
        <h2 class="is-size-4">How do we protect your information?</h2>
        <p>
            We do not use vulnerability scanning and/or scanning to PCI standards.
            An external PCI compliant payment gateway handles all CC transactions.
            We do not use Malware Scanning.
        </p>
        
        <p>Your personal information is contained behind secured networks and is only accessible by a limited number of persons who have special access rights to such systems, and are required to keep the information confidential. In addition, all sensitive/credit information you supply is encrypted via Secure Socket Layer (SSL) technology.</p>
        
        <p>We implement a variety of security measures when a user places an order enters, submits, or accesses their information to maintain the safety of your personal information.</p>

        <p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
        
        <p>All transactions are processed through a gateway provider and are not stored or processed on our servers.</p>
        <br>

        <h2 class="is-size-4">Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)</h2>
        <p>If you are from the European Economic Area (EEA), signyouremail legal basis for collecting and using the personal information
           described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we
           collect it.
        </p>
        <p>signyouremail may process your Personal Data because:</p>
        <ul>
           <li>We need to perform a contract with you</li>
           <li>You have given us permission to do so</li>
           <li>The processing is in our legitimate interests and it's not overridden by your rights</li>
           <li>For payment processing purposes</li>
           <li>To comply with the law</li>
        </ul>
        <br>
        <h2 class="is-size-4">Retention of Data</h2>
        <p>signyouremail will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy
           Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations
           (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce
           our legal agreements and policies.
        </p>
        <p>signyouremail will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter
           period of time, except when this data is used to strengthen the security or to improve the functionality of our
           Service, or we are legally obligated to retain this data for longer time periods.
        </p>
        <br>
        <h2 class="is-size-4">Transfer Of Data</h2>
        <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside
           of your state, province, country or other governmental jurisdiction where the data protection laws may differ
           than those from your jurisdiction.
        </p>
        <p>If you are located outside United States and choose to provide information to us, please note that we transfer the
           data, including Personal Data, to United States and process it there.
        </p>
        <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to
           that transfer.
        </p>
        <p>signyouremail will take all steps reasonably necessary to ensure that your data is treated securely and in accordance
           with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country
           unless there are adequate controls in place including the security of your data and other personal information.
        </p>
        <br>
        <h2 class="is-size-4">Disclosure Of Data</h2>
        <h3 class="is-size-5">Legal Requirements</h3>
        <p>signyouremail may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul>
           <li>To comply with a legal obligation</li>
           <li>To protect and defend the rights or property of signyouremail</li>
           <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
           <li>To protect the personal safety of users of the Service or the public</li>
           <li>To protect against legal liability</li>
        </ul>
        <br>
        <h2 class="is-size-4">Security Of Data</h2>
        <p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method
           of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal
           Data, we cannot guarantee its absolute security.
        </p>
        <br>
        <h2 class="is-size-4">Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h2>
        <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. signyouremail aims
           to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
        </p>
        <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems,
           please contact us.
        </p>
        <p>In certain circumstances, you have the following data protection rights:</p>
        <ul>
           <li>
              <p>
                 <strong>The right to access, update or to delete the information we have on you.</strong> Whenever made possible,
                 you can access, update or request deletion of your Personal Data directly within your account settings
                 section. If you are unable to perform these actions yourself, please contact us to assist you.
              </p>
           </li>
           <li>
              <p>
                 <strong>The right of rectification.</strong> You have the right to have your information rectified if that information
                 is inaccurate or incomplete.
              </p>
           </li>
           <li>
              <p>
                 <strong>The right to object.</strong> You have the right to object to our processing of your Personal Data.
              </p>
           </li>
           <li>
              <p>
                 <strong>The right of restriction.</strong> You have the right to request that we restrict the processing of your
                 personal information.
              </p>
           </li>
           <li>
              <p>
                 <strong>The right to data portability.</strong> You have the right to be provided with a copy of the information
                 we have on you in a structured, machine-readable and commonly used format.
              </p>
           </li>
           <li>
              <p>
                 <strong>The right to withdraw consent.</strong> You also have the right to withdraw your consent at any time
                 where signyouremail relied on your consent to process your personal information.
              </p>
           </li>
        </ul>
        <p>Please note that we may ask you to verify your identity before responding to such requests.</p>
        <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data.
           For more information, please contact your local data protection authority in the European Economic Area (EEA).
        </p>
        <br>

        <h2 class="is-size-4">Log Data</h2>
        <p>We may also collect information that your browser sends whenever you visit our Service ("Log Data"). This Log Data may include information such as your computer's Internet Protocol ("IP") address, browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages and other statistics.</p>
        <p>In addition, we may use third party services such as Google Analytics that collect, monitor and analyze this type of information in order to increase our Service's functionality. These third party service providers have their own privacy policies addressing how they use such information.</p>
        <br>

        <h2 class="is-size-4">Do we use 'cookies'?</h2>
        <p>Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your Web browser (if you allow) that enables the site's or service provider's systems to recognize your browser and capture and remember certain information. For instance, we use cookies to help us remember and process the items in your shopping cart. They are also used to help us understand your preferences based on previous or current site activity, which enables us to provide you with improved services. We also use cookies to help us compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.</p>
        
        <p>We use cookies to:
            • Understand and save user's preferences for future visits.
            • Keep track of advertisements.
        • Compile aggregate data about site traffic and site interactions in order to offer better site experiences and tools in the future. We may also use trusted third-party services that track this information on our behalf.</p>
        
        <p>You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser settings. Since browser is a little different, look at your browser's Help Menu to learn the correct way to modify your cookies.</p>
        
        <p>If users disable cookies in their browser:</p>
        
        <p>If you turn cookies off, Some of the features that make your site experience more efficient may not function properly.Some of the features that make your site experience more efficient and may not function properly.</p>
        
        <br>
        <h2 class="is-size-4">Third-party disclosure</h2>
        
        <p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>
        
        <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
        <br>

        <h2 class="is-size-4">Third-party links</h2>
        <p>Occasionally, at our discretion, we may include or offer third-party products or services on our website. These third-party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.</p>
        
        <p>Google</p>
        
        <p>Google's advertising requirements can be summed up by Google's Advertising Principles. They are put in place to provide a positive experience for users. <a href="https://support.google.com/adwordspolicy/answer/1316548?hl=en">https://support.google.com/adwordspolicy/answer/1316548?hl=en</a> </p>
        
        <p>We use Google AdSense Advertising on our website.</p>
        
        <p>Google, as a third-party vendor, uses cookies to serve ads on our site. Google's use of the DART cookie enables it to serve ads to our users based on previous visits to our site and other sites on the Internet. Users may opt-out of the use of the DART cookie by visiting the Google Ad and Content Network privacy policy.</p>
        
        <p>We have implemented the following:</p>
        <p>
            • Remarketing with Google AdSense
            • Demographics and Interests Reporting
        </p>
        
        <p>We, along with third-party vendors such as Google use first-party cookies (such as the Google Analytics cookies) and third-party cookies (such as the DoubleClick cookie) or other third-party identifiers together to compile data regarding user interactions with ad impressions and other ad service functions as they relate to our website.</p>
        <br>
        <p>Other Third-Party Services Include:</p>
        <p>Google (data processing, marketing, analytics and statistics)</p>
        <p>Fastspring (Payment Processing and Billing)</p>
        <p>Mailgun (Email Marketing)</p>
        <p>Facebook (data processing, marketing, analytics and statistics)</p>
        <p>Bugsnag (Error Reporting)</p>
        <p>Amazon (web and server hosting services)</p>
        <p>DigitalOcean (web and server hosting services)</p>
        <br>
        <p>Opting out:</p>
        <p>Users can set preferences for how Google advertises to you using the Google Ad Settings page. Alternatively, you can opt out by visiting the Network Advertising Initiative Opt Out page or by using the Google Analytics Opt Out Browser add on.</p>
        <br>
        <h2 class="is-size-4">California Online Privacy Protection Act</h2>
        
        <p>CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law's reach stretches well beyond California to require any person or company in the United States (and conceivably the world) that operates websites collecting Personally Identifiable Information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals or companies with whom it is being shared. - See more at: http://consumercal.org/california-online-privacy-protection-act-caloppa/#sthash.0FdRbT51.dpuf</p>
        
        <br>
        <h2 class="is-size-4">According to CalOPPA, we agree to the following:</h2>
        <p>
            Users can visit our site anonymously.
            Once this privacy policy is created, we will add a link to it on our home page or as a minimum, on the first significant page after entering our website.
            Our Privacy Policy link includes the word 'Privacy' and can easily be found on the page specified above.
        </p>
        <p>
            You will be notified of any Privacy Policy changes:
            • On our Privacy Policy Page
            Can change your personal information:
            • By logging in to your account
        </p>
        <br>
        <h2 class="is-size-4">How does our site handle Do Not Track signals?</h2>
        <p>We don't honor Do Not Track signals and Do Not Track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place. We don't honor them because:
        we use third party services which may or may not respect DNT signals</p>
        <br>
        <h2 class="is-size-4">Does our site allow third-party behavioral tracking?</h2>
        <p>It's also important to note that we allow third-party behavioral tracking</p>
        <br>
        <h2 class="is-size-4">COPPA (Children Online Privacy Protection Act)</h2>
        
        <p>When it comes to the collection of personal information from children under the age of 13 years old, the Children's Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission, United States' consumer protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to protect children's privacy and safety online.</p>
        <br>
        <h2 class="is-size-4">Do we let third-parties, including ad networks or plug-ins collect PII from children under 13?</h2>
        <p>We do not specifically market to children under the age of 13 years old.</p>
        <br>
        <h2 class="is-size-4">Fair Information Practices</h2>
        
        <p>The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe. Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information.</p>
        <p>
            In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach occur:
            We will notify you via email
            • Within 7 business days
        </p>
        
        <p>We also agree to the Individual Redress Principle which requires that individuals have the right to legally pursue enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users, but also that individuals have recourse to courts or government agencies to investigate and/or prosecute non-compliance by data processors.</p>
        <br>
        <h2 class="is-size-4">CAN SPAM Act</h2>
        
        <p>The CAN-SPAM Act is a law that sets the rules for commercial email, establishes requirements for commercial messages, gives recipients the right to have emails stopped from being sent to them, and spells out tough penalties for violations.</p>
        <p>
            We collect your email address in order to:
            • Send information, respond to inquiries, and/or other requests or questions
            • Process orders and to send information and updates pertaining to orders.
            • Send you additional information related to your product and/or service
            • Market to our mailing list or continue to send emails to our clients after the original transaction has occurred.
        </p>
        <p>
            To be in accordance with CANSPAM, we agree to the following:
            • Not use false or misleading subjects or email addresses.
            • Identify the message as an advertisement in some reasonable way.
            • Include the physical address of our business or site headquarters.
            • Monitor third-party email marketing services for compliance, if one is used.
            • Honor opt-out/unsubscribe requests quickly.
            • Allow users to unsubscribe by using the link at the bottom of each email.
        </p>
        
        <p>
            If at any time you would like to unsubscribe from receiving future emails, you can email us at
        </p>
        <p>
            • Follow the instructions at the bottom of each email.
            and we will promptly remove you from ALL correspondence.
        </p>
        <br>
        
        <h2 class="is-size-4">Contact Us</h2>
        <p>If there are any questions regarding this privacy policy, you may contact us using the information below.</p>
        <p>Email: support@signyouremail.io</p>
  
    </div>
</section>
<?php  echo get_footer(); ?>